// <auto-generated />
namespace VNC_PT_APPLICATION.Persistence.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MoreDatatypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreDatatypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201904220437404_MoreDatatypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
